### PR TITLE
perf: Reduce calls to session.get in logo_click and update_last_index…

### PR DESCRIPTION
**Pull request by bbimams**
… routes

### CODE REVIEW

**Comment by Jay-1409** [comment]
please create an issue first thank you !!

**Comment by Jay-1409** [comment]
I hope you have checked that it wont create any functionality issues, if then I will merge it?

**Comment by bbimams** [comment]
> I hope you have checked that it wont create any functionality issues, if then I will merge it?

ofc not, all good

**Comment by Jay-1409** [comment]
ok thank you

**Pull request merged**
