### PR TITLE
added the scroll_bar for future use also made some changes 

### PR DESCRIPTION
**Pull request by ARRY7686**
### Description
Added the scroll_bar for future use also made some CSS changes so that all the characters can come in the vh.This solves issue #11

### CODE REVIEW

**Comment by ARRY7686** [comment]
@Jay-1409 pls see to it and merge it accordingly

**Comment by Jay-1409** [comment]
Sure and can you please send some screen shots of what you have done ?

**Comment by ARRY7686** [comment]
image

before franklin and trevor were not visible which was a bad UX after making them inside the vh the user can use those bots also

added a scroll bar in case u want to add a footer and more things in the bottom

**Comment by ARRY7686** [comment]
@Jay-1409

**Comment by Jay-1409** [comment]
i think adding the scroll bar might cause visibility issues in smaller devices

**Comment by ARRY7686** [comment]
In small devices the scroll-bar would be of more importance as the 100vh could not take the screen size and tge users have to scroll down

**Comment by ARRY7686** [comment]
Can I get an update on the merging status @Jay-1409

**Pull request merged**
