### PR TITLE
Issue of Responsiveness is solved

### PR DESCRIPTION
**Pull request by Jils31**
This pull request addresses and resolves the responsiveness issues present in the different pages of the website. The goal was to ensure that all the pages and its elements display correctly across various screen sizes and devices, improving the overall user experience.

These updates enhance the user experience for users accessing the login page on various devices. With the improved responsiveness, the application is now more user-friendly and accessible.

### CODE REVIEW

**Comment by Jay-1409** [comment]
okay let me check it out.

**Comment by Jils31** [comment]
Hey!, I want to work more on the responsiveness of the page as i can create a hamburger menu which makes it more interactive for an user if he/she is reviewing the website on the smaller devices

**Comment by Jay-1409** [comment]
Umm but for the normal desktop the navbar would look better right ? so will it switch to hamburger menu or something ? looks like a good idea though

**Comment by Jils31** [comment]
If the size of the screen is small enough then it will switch to the hamburger menu and it will make the website more good looking

**Comment by Jay-1409** [comment]
> If the size of the screen is small enough then it will switch to the hamburger menu and it will make the website more good looking

okayy that sounds good!!! proceed with it..

**Comment by Jils31** [comment]
So i create a new issue for creating the hamburger menu please assign that issue to me, I'll make this thing work for you

**Comment by Jay-1409** [comment]
> So i create a new issue for creating the hamburger menu please assign that issue to me, I'll make this thing work for you

okayy

**Pull request merged**
